drop database trabajofin;
create database  trabajofin;

use trabajofin;

create table  juegos
(id_juego int primary key auto_increment,
 nombre varchar(255),
 genero varchar(255),
 plataforma varchar(255),
 comentarios varchar(1000),
 link varchar(1000));
 
 create table if not exists usuario
 (id_usuario int primary key auto_increment,
 nombre_usuario varchar(255),
 pass varchar(255),
 tipo_usuario tinyint);
 
INSERT INTO usuario (nombre_usuario, pass,tipo_usuario) VALUES ('Admin', '1234','0');

 
/*deportes, aventura, tiros, rol*/

/*SWITCH*/

INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Mario Kart 8', 'Deportes','Nintendo - Switch','Las carreras más locas y divertidas de Nintendo llegan a Wii U en esta esperada entrega, la primera en alta definición, en un juego que trata de plasmar lo que ya nos encandiló de sus predecesores junto a una nueva vuelta de tuerca: la antigravedad.','https://www.eneba.com/nintendo-mario-kart-8-deluxe-nintendo-switch-eshop-key-europe');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Mario Party', 'Aventura','Nintendo - Switch','Mario Party es una serie de videojuegos en los que cuatro personajes del universo de Mario, controlados por personas o por la consola, compiten en un juego de tablero, utilizando dados para moverse en casillas y participando en múltiples minijuegos. Desde los comienzos de la serie hasta Mario Party 8 y Mario Party DS (ambos de 2007), los videojuegos han sido desarrollados por Hudson Soft y publicados por Nintendo','https://www.eneba.com/mario-party-8-wii');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Smash Bros. Ultimate', 'deportes','Nintendo - Switch','Super Smash Bros. Ultimate, permite a ocho jugadores enfrentarse en combates cargados de acción en los que el objetivo es catapultar a populares personajes de los videojuegos fuera de la pantalla.Super Smash Bros. Ultimate incluirá todos y cada uno de los jugadores que han estado presentes en las casi dos décadas de historia de la serie.','https://www.eneba.com/nintendo-super-smash-bros-ultimate-fighters-pass-vol-2-dlc-nintendo-switch-eshop-key-united-states ');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Metroid Prime', 'Shooter','Nintendo - Switch','VUELVE A PONERTE EL TRAJE ¡Conviértete en el cazarrecompensas Samus Aran una vez más en Metroid Prime Remastered! La aventura en primera persona aclamada por la crítica ha sido renovada para Nintendo Switch. LA AVENTURA CLÁSICA, REBORN Tranquila y capaz, Samus asume esta misión en solitario... pero no está sola. Ponte sus botas mientras navegas por caminos sinuosos y entornos interconectados de un planeta alienígena atractivo pero peligroso.','https://www.eneba.com/nintendo-metroid-prime-remastered-nintendo-switch-eshop-key-united-states');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Kirby y la tierra olvidada', 'Aventura','Nintendo - Switch','El poderoso y monísimo héroe rosa de Nintendo, Kirby, regresa en Kirby y la tierra olvidada, donde hará gala de nuevas habilidades en una aventura de plataformas en 3D llena de colorido, sorpresas, naturaleza salvaje y ¡Waddle Dees para dar y tomar!','https://www.eneba.com/kirby-and-the-forgotten-land-nintendo-switch');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Pokemon escarlata', 'Rol','Nintendo - Switch','Pokémon Escarlata y Pokémon Púrpura serán los primeros RPG de mundo abierto de la saga Pokémon. Podrás seguir disfrutando de los clásicos de siempre, como descubrir Pokémon, entrenarlos, intercambiarlos, combatir y formar tu equipo con ellos, mientras te sumerges en esta enrome y nueva aventura.','https://www.eneba.com/steelbook-pokemon-escarlata-nuevo-e6adb090');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Octopath Traveler', 'Rol','Nintendo - Switch','Un juego de rol de la saga OCTOPATH TRAVELER, que toma las bases de los gráficos HD-2D de la serie.
Ocho viajantes del mundo de Solistia emprenden un viaje mientras se adentran en una apasionante época.','https://www.eneba.com/steam-octopath-traveler-ii-pc-steam-key-global');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Switch Sports', 'Deportes','Nintendo - Switch','¡Los jugadores tendrán que lograr la victoria con raquetazos, patadas y remates en esta colección de deportes que les sitúa en el centro de la acción!. Podrán jugar en persona o en línea con familiares y amigos, o desafiar a jugadores del mundo entero en esta nueva entrega de la serie clásica Wii Sports. Disfruta de seis deportes, incluidos voleibol, fútbol y bolos. Los movimientos que hagas en el mundo real se reproducirán dentro del juego.
','https://www.eneba.com/nintendo-switch-sports-nintendo-switch');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('The legend of Zelda breath of the wild', 'Aventura','Nintendo - Switch','Olvida todo lo que sabes sobre los juegos de The Legend of Zelda. Entra en un mundo de descubrimientos, exploración y aventura en The Legend of Zelda: Breath of the Wild, un juego de la serie que rompe con las convenciones. Viaja por prados, bosques y cumbres montañosas para descubrir qué ha sido del asolado reino de Hyrule en esta aventura a cielo abierto.','https://www.eneba.com/nintendo-the-legend-of-zelda-breath-of-the-wild-expansion-pass-dlc-nintendo-switch-eshop-key-europe');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Splatoon 3', 'Shooter','Nintendo - Switch','¡Entinta y sobrevive en Splatoon 3! Te damos la bienvenida a la abrasadora región de Tintelia, ¡donde te esperan nuevas armas, habilidades, escenarios e indumentaria de lo más novedoso!. Adéntrate en una zona desértica con un sol abrasador habitada por aguerridos inklings y octolings. ¡Entinta, sumérgete, nada y salpica en tu camino hacia la cima!','https://www.eneba.com/nintendo-splatoon-3-nintendo-switch-eshop-key-united-states-1');

/* PS5*/

INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Crash Bandicoot 4', 'Aventura','Play Station','¡Neo Cortex y N. Tropy están de vuelta, iniciando un ataque definitivo no solo en este universo, sino en todo el multiverso! Crash y Coco están aquí para evitar la catástrofe reuniendo las cuatro máscaras cuánticas y rompiendo las reglas de la realidad. ¿Habilidades nuevas? Compruébalas.','https://www.eneba.com/crash-bandicoot-4-its-about-time-nintendo-switch');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Fifa 23', 'Deportes','Play Station','EA SPORTS FIFA 23 nos acerca aún más a la acción y el realismo del juego del mundo gracias a la tecnología HyperMotion 2, con el doble de capturas de movimiento del mundo real y animaciones más auténticas que nunca en cada partido. Disputa los torneos importantes del fútbol.','https://www.eneba.com/origin-fifa-23-pc-origin-key-global');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Call of duty modern warfare 2', 'Shooter','Play Station','Infinity Ward sumergirá a los fans en una emocionante experiencia puntera de nueva generación. Lucha con amigos en esta nueva experiencia inmersiva que cuenta con un audio, una iluminación y unos gráficos realistas.','https://www.eneba.com/steam-call-of-duty-modern-warfare-2-resurgence-pack-dlc-steam-key-global');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Gran turismo 7', 'Deportes','Play Station','Desde los vehículos y circuitos más clásicos hasta la reincorporación del legendario modo Simulación GT, disfruta de las mejores funcionalidades de las anteriores entregas de la serie. El 4 de abril, Japan Race Promotion (JRP), los organizadores del Campeonato de Super Formula Japonesa (Super Formula), anunciaron una nueva colaboración con Polyphony Digital.','https://www.eneba.com/psn-gran-turismo-7-25th-anniversary-edition-ps4-psn-key-europe');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Hogwards Legacy', 'Rol','Play Station','Hogwarts Legacy es un juego de rol de acción inmersivo de mundo abierto para un solo jugador ambientado en el mundo mágico del siglo XIX.','https://www.eneba.com/hogwarts-legacy-playstation-5');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('God of War Ragnarok', 'Aventura','Play Station','De la mano de Santa Monica Studio llega la secuela del aclamado God of War (2018). El Fimbulvetr está en marcha. Kratos y Atreus deben viajar a cada uno de los Nueve Reinos en busca de respuestas mientras las fuerzas asgardianas se preparan para la batalla profetizada que supondrá el fin del mundo. Por el camino, explorarán paisajes míticos increíbles y se enfrentarán a temibles enemigos, como monstruos y dioses nórdicos. La amenaza del Ragnarök está cada vez más cerca. Kratos y Atreus deben elegir entre su propia seguridad y la de los reinos.','https://www.eneba.com/god-of-war-ragnarok-playstation-4');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Elden Ring', 'Rol','Play Station','La Orden Dorada está rota. Álzate, Sinluz, y que la gracia te guíe para abrazar el poder del Círculo de Elden y encumbrarte como señor del Círculo en las Tierras Intermedias. ELDEN RING es un juego de rol y acción de ambientación fantástica desarrollado por FromSoftware Inc. y producido por BANDAI NAMCO Entertainment Inc.','https://www.eneba.com/elden-ring-playstation-4');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Battlefield 2042', 'Shooter','Play Station','Battlefield 2042 es un shooter en primera persona que marca el regreso a la emblemática guerra total de la franquicia. En un mundo en el futuro cercano transformado por el desorden, adáptate y sobrevive con la ayuda de tu patrulla y un arsenal de vanguardia en campos de batalla en constante cambio. Con partidas de 128 jugadores, Battlefield 2042 ofrece una escala sin precedentes en inmensos entornos por todo el mundo','https://www.eneba.com/origin-battlefield-2042-pc-origin-key-europe');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Tekken 7', 'Deportes','Play Station','Tekken 7 es el capítulo final de la historia sanguinaria de la familia Mishima, donde las batallas finales entre sus miembros, y no solo, ponen en peligro al mundo entero. Los duelos épicos de la serie continúan con un guión inmersivo y escenas cinematográficas increíbles, que se ven reforzadas por el motor gráfico Unreal Engine 4, que crea gráficos casi fotorrealistas','https://www.eneba.com/steam-tekken-7-steam-key-ru-cis');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Star Wars Jedi Survivor', 'Rol','Play Station','Continúa el viaje de Cal: Cal ya no es un padawan y se ha convertido en un poderoso caballero Jedi; Lleva consigo los recuerdos y las expectativas de la orden Jedi y su cruzada contra el imperio se ha ido tornando cada vez más peligrosa; Se acercan tiempos oscuros; Rodeado de s y viejos enemigos, tendrá que decidir hasta dónde está dispuesto a llegar para salvar a sus seres queridos','https://www.eneba.com/origin-star-wars-jedi-survivortm-pc-origin-key-global');

/*PC*/

INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Diablo IV', 'Rol','Ordenador','Diablo® IV es un RPG de acción de nueva generación en el que deberás acabar con incontables males, dominar un sinfín de facultades, superar mazmorras de pesadilla y obtener botín legendario. Embárcate por tu cuenta o con amigos, conoce personajes memorables en escenarios siniestros y una historia fascinante.','https://www.eneba.com/other-diablo-r-iv-early-access-beta-https-diablo4-blizzard-com-beta-key-global');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Ark Survival Evolved', 'Aventura','Ordenador','¡Prepárate para una aventura con dinosaurios insuperable. Varado en una misteriosa isla prehistórica, tendrás que explorar sus inmensos biomas a medida que cazas, cosechas, creas herramientas, cultivas y construyes refugios para sobrevivir. Usa tu ingenio y habilidad para matar, domesticar, criar e incluso montar dinosaurios y otras bestias primitivas que viven en “ARK”.','https://www.eneba.com/steam-ark-survival-evolved-steam-key-global');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Doom', 'Shooter','Ordenador','DOOM: Eres uno de los marines más duros de la Tierra estacionado en Marte cuando un experimento militar abre las puertas al infierno; depende de ti derrotar a las hordas de demonios con un arsenal de armas brutales en DOOM, el juego que fue pionero en el género del shooter en primera persona y cambió los videojuegos para siempre','https://www.eneba.com/steam-doom-steam-key-europe');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Fortnite', 'Shooter','Ordenador','Conviértete en una bocanada de aire fresco con el pack de Leyendas de Menta. Incluye: Traje de Aura fresca, Accesorio mochilero Multimochila mentolada, Pico Montañista mentolado, Traje de Bombardera mentolada, Accesorio mochilero Macuto mentolado, Pico Rompefrescuras, Traje de Oro esquelementa, Accesorio mochilero Manto mentolado, Pico Cetro triplementa, Envoltorio Menta ardiente y 1000 paVos. Pon a prueba tus habilidades y crea juegos con las herramientas del modo Creativo de Fortnite, disponibles para consola, PC y dispositivos móviles','https://www.eneba.com/fortnite-nintendo-switch');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Fallout 76', 'Rol','Ordenador','GAME te trae Fallout 76 para PlayStation 4, Xbox One y PC. Sobrevive al yermo y al resto de moradores, de forma cooperativa o solo en este juego de Rol/Acción. ¡El trabajo en equipo te dará mayores posiblidades de sobrevivir! Bethesda Game Studios, los galardonados creadores de Skyrim y Fallout 4, te dan la bienvenida a Fallout 76','https://www.eneba.com/bethesda-fallout-76-bethesda-net-key-global');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Rocket league', 'Deportes','Ordenador','La temporada 10  te invita a poner el punto muerto mientras descansas, te relajas y consigues un montón de objetos. Disfruta de un tranquilo Rocket Pass, explora la nueva variante de la arena Oasis y llévate el legendario Volkswagen Golf II GTI a dar una vuelta. La personalización reina en el barrio, y muchas tiendas locales de tuneo han diseñado sus propios packs de calcomanías para el Dingo, el Breakout, el Fennec, el Dominus y el Octane. Las calles son tuyas, así que ve a por ellas. ¡Neotokio: Aftermarket estará disponible del 20 de marzo al 3 de abril!','https://www.eneba.com/steam-rocket-league-steam-key-global');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Counter strike global ofensive', 'Shooter','Ordenador','Counter-Strike: Global Offensive (CS: GO) amplía el juego de acción en equipo del que fue pionero cuando se lanzó hace 19 años. CS: GO presenta nuevos mapas, personajes, armas y modos de juego, y ofrece versiones actualizadas del contenido clásico de CS (de_dust2, etc.).','https://www.eneba.com/steam-counter-strike-global-offensive-steam-key-asia');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Grounded', 'Aventura','Ordenador','El mundo es un lugar vasto, hermoso y peligroso, especialmente cuando te has reducido al tamaño de una hormiga. ¿Puedes prosperar junto a las hordas de insectos gigantes, luchando para sobrevivir a los peligros del patio trasero?. Juega solo o en compañía, online, de hasta tres amigos. ¡Con la característica Mundos compartidos, puedes continuar jugando con todo tu progreso guardado!. Se pueden encontrar criaturas vagando por el patio en una multitud de entornos. Incluso puedes atraerlas a diferentes lugares activando los dispositivos MIX.R. Pero cuanto más interfieras, mayor será la probabilidad de que vengan a llamar a tu puerta. Usa los sistemas de personalización del juego, como Mutaciones o Muelas de leche para activar las bonificaciones y ventajas que quieres para tu personaje.','https://www.eneba.com/steam-groundhog-day-like-father-like-son-vr-steam-key-global ');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Hades', 'Aventura','Ordenador','Desafía al dios de los muertos mientras cortas y acuchillas fuera del inframundo en este juego de exploración de mazmorras pícaro de los creadores de Bastion, Transistor y Pyre.','https://www.eneba.com/hades-2018-playstation-5');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Hot Wheels Unleashed', 'Deportes','Ordenador','Colecciona los mejores vehículos del universo Hot Wheels™, construye pistas espectaculares y sumérgete en carreras impresionantes.','https://www.eneba.com/hot-wheels-unleashed-playstation-5');

/*XBOX*/

INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Halo 5', 'Shooter','Xbox','Cuando se pierde toda esperanza y el destino de la humanidad pende de un hilo, el Jefe Maestro está listo para enfrentarse al enemigo más despiadado que jamás haya enfrentado. Métete en la armadura del héroe más grande de la humanidad para vivir una aventura épica y explorar la enorme escala del anillo de Halo.','https://www.eneba.com/xbox-gears-of-war-4-and-halo-5-guardians-bundle-xbox-live-key-turkey');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Gears of war 5', 'Shooter','Xbox','De una de las sagas de juegos más aclamadas, Gears es más grande que nunca. Con la guerra total descendiendo, Kait Diaz se separa para descubrir su conexión con el enemigo y descubre el verdadero peligro para Sera: ella misma. De una de las sagas más aclamadas de la historia de los videojuegos, la célebre campaña de Gears 5 y el renovado modo multijugador están totalmente optimizados para Xbox Series X y Series S..','https://www.eneba.com/xbox-gears-5-ultimate-edition-gears-of-war-4-bundle-pc-xbox-one-xbox-live-key-global');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Forza motosport 7', 'Deportes','Xbox','¡Tu Ultimate Horizon Adventure te espera! Explore los vibrantes paisajes de mundo abierto de México con acción de conducción ilimitada y divertida en los mejores autos del mundo. Conquista la escarpada Sierra Nueva en la mejor experiencia de Horizon Rally.','https://www.eneba.com/xbox-forza-motorsport-7-xbox-live-key-brazil');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Sea of thieves', 'Aventura','Xbox','Celebre cinco años desde el lanzamiento de Sea of ​​Thieves con esta edición especial, que incluye una copia del juego con todo el contenido permanente agregado desde el lanzamiento, además de una bonificación de 10,000 de oro y una selección de cosméticos Hunter: Hunter Cutlass, Pistol','https://www.eneba.com/steam-sea-of-thieves-sails-of-the-bonny-belle-dlc-pc-steam-key-global');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Titanfall 2', 'Shooter','Xbox','Respawn Entertainment te ofrece la tecnología Titan más avanzada en su nueva campaña para un jugador y experiencia multijugador. Combina y conquista con nuevos titanes y pilotos, armas más letales y sistemas de personalización y progresión que te ayudan a ti y a tu titán ','https://www.eneba.com/origin-titanfall-2-pl-ru-origin-key-global');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Ori and the Will of the Wisp', 'Aventura','Xbox','Juega la obra maestra aclamada por la crítica. Embárcate en un nuevo viaje en un vasto y exótico mundo donde te encontrarás con imponentes enemigos y desafiantes acertijos en tu búsqueda para desentrañar el destino de Ori.','https://www.eneba.com/xbox-ori-and-the-will-of-the-wisps-pc-xbox-live-key-turkey');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Assassins Creed Valhalla', 'Aventura','Xbox','Conviértete en un vikingo legendario en busca de la gloria. Asalta a tus enemigos, haz crecer tu asentamiento y construye tu poder político.','https://www.eneba.com/uplay-assassins-creed-valhalla-season-pass-dlc-uplay-key-europe');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Yakuza like a Dragon', 'Rol','Xbox','Conviértete en Ichiban Kasuga, un soldado yakuza de bajo rango dejado al borde de la muerte por el hombre en el que más confiaba. Toma tu legendario bate y prepárate para romper algunos cráneos del inframundo en un dinámico juego de rol de combate ambientado en el Japón moderno','https://www.eneba.com/steam-yakuza-like-a-dragon-day-ichi-edition-steam-key-europe');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('Persona 5 Royale', 'Rol','Xbox','Rompe las cadenas de la sociedad moderna e infíltrate en las mentes de los corruptos para hacerles cambiar de vida. Persona 5 Royal viene con nuevos personajes, confidentes, historia nueva, lugares nuevos que explorar, etc.','https://www.eneba.com/steam-persona-5-royal-pc-steam-key-europe');
INSERT INTO juegos (nombre,genero,plataforma,comentarios,link) VALUES ('NBA 2k23', 'Deportes','Xbox','disfruta de la mejor liga de baloncesto del mundo en tu consola gracias a 2K, compite con tus equipos y estrellas favoritas de la NBA y la WNBA, crea tu jugador y experimenta el máximo de la jugabilidad real.','https://www.eneba.com/steam-nba-2k23-pc-steam-key-global-2');

select * from juegos;
SELECT * FROM usuario;


